name: yatube workflow

on: [push]

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Logint to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/yatube:latest
        

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    
    - uses: actions/checkout@v2
    
    - name: create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_HOST: ${{ secrets.HOST }}
        envkey_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        
    - name: copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "docker-compose.yaml, nginx.conf, .env"
        target: "yatube"
      
    - name: executing remote ssh comands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd yatube
          sudo docker-compose pull web
          sudo docker-compose up -d
          sudo docker image prune -f
